# Configuration file for typos
# See https://github.com/crate-ci/typos for more information

[default.extend-words]
oif = "oif"
nd = "nd"
onl = "onl"
thr = "thr"
rto = "rto"
seh = "seh"
flushed = "flushed"
FLUSHed = "FLUSHed"
lso = "lso"
inport = "inport"
sigfault = "sigfault"
iif = "iif"
reseted = "reseted"
ect = "ect"
treshold = "treshold"
LD_PRELOADed = "LD_PRELOADed"
ERRORs = "ERRORs"
INLINEing = "INLINEing"
clen = "clen"
useg = "useg"
CLASSE = "CLASSE"
PARMS = "PARMS"
typ = "typ"
TIMis = "TIMis"
BA = "BA"

[default.extend-identifiers]
oif = "oif"
nd = "nd"
onl = "onl"
thr = "thr"
rto = "rto"
seh = "seh"
flushed = "flushed"
FLUSHed = "FLUSHed"
lso = "lso"
inport = "inport"
sigfault = "sigfault"
iif = "iif"
reseted = "reseted"
ect = "ect"
treshold = "treshold"
LD_PRELOADed = "LD_PRELOADed"
ERRORs = "ERRORs"
INLINEing = "INLINEing"
clen = "clen"
useg = "useg"
CLASSE = "CLASSE"
PARMS = "PARMS"
typ = "typ"
TIMis = "TIMis"
BA = "BA"
